apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-classifier
  namespace: intent-namespace
  labels:
    app: intent-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intent-classifier
  template:
    metadata:
      labels:
        app: intent-classifier
    spec:
      containers:
        - name: intent-classifier
          image: us-east4-docker.pkg.dev/namalas-test00/intent-classifier-model/model-image:1.0
          ports:
            - containerPort: 6000
